practiceapp/src/main/java/com/practiceapp/practiceapp/entity/CommunityEntity.java
practiceapp/src/main/java/com/practiceapp/practiceapp/entity/PostEntity.java
practiceapp/src/main/java/com/practiceapp/practiceapp/entity/UserEntity.java
practiceapp/src/main/java/com/practiceapp/practiceapp/repository/CommunityRepository.java

The community entity class is implemented and other entity classes are updated. Please review.

Iremzeynepalagoz

---

practiceapp/src/main/java/com/practiceapp/practiceapp/controller/community/CreateCommunityController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/entity/CommunityEntity.java
practiceapp/src/main/java/com/practiceapp/practiceapp/service/CommunityService.java
practiceapp/src/main/java/com/practiceapp/practiceapp/utils/DetectLanguageApi.java

Implemented API for **Creating Community**. Used [third-party API](https://detectlanguage.com/)  to detect the language of the community from its description. Updated Community Entity.

Community Entity and Creating Community API 

---

practiceapp/src/main/java/com/practiceapp/practiceapp/controller/user/CreateUserController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/entity/Profile.java
practiceapp/src/main/java/com/practiceapp/practiceapp/entity/UserEntity.java
practiceapp/src/main/java/com/practiceapp/practiceapp/repository/ProfileRepository.java
practiceapp/src/main/java/com/practiceapp/practiceapp/service/ProfileService.java
practiceapp/src/main/java/com/practiceapp/practiceapp/service/UserService.java

I created an entity, service and repository for profile.  Updating profile request successfully works.

Profile Entity and Update Profile Function

---

practiceapp/src/main/java/com/practiceapp/practiceapp/controller/profile/ProfileController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/user/CreateUserController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/utils/PicturesApi.java

Created a profile controller, a new get profile function and the third-party api
Moved the update profile function to the new controller

Profile Controller

---

practiceapp/pom.xml
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/community/GetCommunityController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/universitieslist/UniversitiesListController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/service/CommunityService.java
practiceapp/src/main/java/com/practiceapp/practiceapp/utils/UniversitiesListApi.java

Implemented the function to get communities by name. Added a third party api to get the list of universities of a given country with related information.

Implemented API functionality: Get community by name

---

practiceapp/src/main/java/com/practiceapp/practiceapp/controller/community/CreateCommunityController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/entity/CommunityEntity.java
practiceapp/src/main/java/com/practiceapp/practiceapp/repository/CommunityRepository.java
practiceapp/src/main/java/com/practiceapp/practiceapp/service/CommunityService.java
practiceapp/src/main/java/com/practiceapp/practiceapp/utils/DetectLanguageApi.java
practiceapp/src/test/java/com/practiceapp/practiceapp/controller/community/CreateCommunityControllerTest.java
practiceapp/src/test/java/com/practiceapp/practiceapp/service/CommunityServiceTest.java

Updated CreatingCommunityController: 
- Detailed Swagger documentation provided
- Made Community name unique
- Return type and status fixed etc.
Added Unit tests for CreatingCommunityController and CommunityService. **Missing tests for the community service about other controllers will be completed**

Updated CreatingCommunityController, Added Unit tests for the controller and community service

---

practiceapp/src/main/java/com/practiceapp/practiceapp/controller/post/CreatePostController.java
practiceapp/src/test/java/com/practiceapp/practiceapp/controller/post/CreatePostControllerTest.java
practiceapp/src/test/java/com/practiceapp/practiceapp/service/PostServiceTest.java

I implemented unit tests for creating posts.

Unit Test Implementation

---

practiceapp/src/main/java/com/practiceapp/practiceapp/controller/community/GetCommunitiesByPublicityController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/entity/CommunityEntity.java

Implemented controller for getting communities by publicity.  
The controller includes the Get method.
This method returns public or private communities based on the selection. 
Selection is done by parameter _public = boolean_.
**true**: Public
**false**: Private
Returns list of community entities.

Implemented getCommunitiesByPublicityController

---

practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/CreateCommunityViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/DictionaryViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/GetCommunityViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/GetPostsViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/IndexViewController.java
practiceapp/src/main/resources/templates/community.html
practiceapp/src/main/resources/templates/community_create_form.html
practiceapp/src/main/resources/templates/community_search_form.html
practiceapp/src/main/resources/templates/dictionary.html
practiceapp/src/main/resources/templates/dictionary_form.html
practiceapp/src/main/resources/templates/posts.html

I implemented the following:
* **Getting communities by name**: I implemented **GetCommunityViewController** as the bridge between frontend and our Rest Controller **GetCommunityController**. In view controller, I implemented functions for viewing the form, retrieving the response from the form and redirection.
* **Getting posts by community name**: I opened a template for post list page as **posts.html**. Then I connected the **GetPostsViewController** with posts template. After getting communities by their name, users will be able to see the posts of that community or another community if they enter.
*  **Dictionary**: We will have an additional page that enables users to enter a word and look up for the definition of that word. I designed the form for that part and connected with …

Frontend Functionality:  Get Posts, Get Communities, Dictionary

---

practiceapp/src/main/java/com/practiceapp/practiceapp/controller/profile/ProfileController.java

Sorry, I just recognized that I forgot the change the name of the one of my functions. It'd be great if you can have a quick review. 
Thank you :)

Function Name Fix

---

practiceapp/src/main/java/com/practiceapp/practiceapp/controller/community/GetCommunitiesByPublicityController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/CreateCommunityViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/GetCommunitiesByPublicityViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/GetCommunityViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/GetPostsViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/IndexViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/entity/CommunityEntity.java
practiceapp/src/main/java/com/practiceapp/practiceapp/repository/CommunityRepository.java
practiceapp/src/main/java/com/practiceapp/practiceapp/service/CommunityService.java
practiceapp/src/main/resources/templates/communities.html
practiceapp/src/main/resources/templates/communities_search_form.html
practiceapp/src/main/resources/templates/community.html
practiceapp/src/main/resources/templates/community_create_form.html
practiceapp/src/main/resources/templates/community_search_form.html
practiceapp/src/main/resources/templates/dictionary_form.html
practiceapp/src/main/resources/templates/index.html
practiceapp/src/main/resources/templates/posts.html
practiceapp/src/test/java/com/practiceapp/practiceapp/controller/community/CreateCommunityControllerTest.java
practiceapp/src/test/java/com/practiceapp/practiceapp/controller/community/GetCommunitiesByPublicityControllerTest.java
practiceapp/src/test/java/com/practiceapp/practiceapp/service/CommunityServiceTest.java

I created file named _getCommunitiesByPublicityControllerTest_ and added under /test/controller/community package.
I implemented unit tests to check the functionality of the controller, specifically the GET method named **getCommunitiesByPublicity**.
Tests control the general functionality of API and check if it is calling the service with a  correct parameter.

Implemented unit tests for getCommunitiesByPublicity

---

practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/CreateCommunityViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/DictionaryViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/GetCommunitiesByPublicityViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/GetCommunityViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/GetPlacesViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/GetPostsViewController.java
practiceapp/src/main/resources/application.yml
practiceapp/src/main/resources/templates/communities_search_form.html

- Added base URL to application.yml. Instead of writing the base URL in every class, used that variable. In this way, when there is a change in our base URL, we will not need to change it in every file.
- Used request parameter instead of path variable in _GetCommunitiesByPublicityViewController_.
- Fixed typo in the template: _communitiesSearchForm_

Fixed URLs and changed path variable to parameter in GetCommunitiesByPublicityViewController

---

practiceapp/src/main/java/com/practiceapp/practiceapp/controller/community/GetPostsController.java
practiceapp/src/test/java/com/practiceapp/practiceapp/controller/community/GetPostsControllerTest.java

* I created a unit test for get posts controller. It controls getPosts function of the controller and the service method.
* Added API Documentation to Get Posts Controller.

Get posts controller test / controller API documentation

---

practiceapp/src/main/java/com/practiceapp/practiceapp/controller/profile/ProfileController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/repository/ProfileRepository.java
practiceapp/src/main/java/com/practiceapp/practiceapp/service/ProfileService.java
practiceapp/src/test/java/com/practiceapp/practiceapp/controller/profile/ProfileControllerTest.java
practiceapp/src/test/java/com/practiceapp/practiceapp/service/ProfileServiceTest.java

I implemented the unit tests for Profile API functionalities (getProfile, updateProfile, setRandomPic) for both in the controller and service. The tests are successfully passed.

Unit tests: Profile Service & Controller

---

practiceapp/src/main/java/com/practiceapp/practiceapp/controller/community/CreateCommunityController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/service/CommunityService.java
practiceapp/src/test/java/com/practiceapp/practiceapp/controller/community/GetCommunitiesByPublicityControllerTest.java
practiceapp/src/test/java/com/practiceapp/practiceapp/controller/community/GetPostsControllerTest.java
practiceapp/src/test/java/com/practiceapp/practiceapp/service/CommunityServiceTest.java

I've done the following changes:
- **CommunitiyServiceTests**: Added missing tests for CommunityServiceTest (except for the _getUniversitiesList_ and _getDefinition_ which are related to third-party APIs)
- **GetCommunitiesByPublicityControllerTest**: Fixed URLs and deleted setId
- **GetPostsControllerTest**: Deleted setting id fields of the post
- **CreateCommunityController**: Wrote detailed Swagger documentation
- **CommunityService**: Deleted unnecessary imports and changed comments to Javadoc
Please review.

Implemented unit tests for CommunityService and wrote more detailed documentation for CreateCommunityController

---

practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/GetKanyeViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/JoinCommunityViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/PostViewController.java
practiceapp/src/main/resources/templates/create_post.html
practiceapp/src/main/resources/templates/get_kanye.html
practiceapp/src/main/resources/templates/join_community.html
practiceapp/src/main/resources/templates/update_post.html

Frontend of joining communitiy, creating post, updating post, getting kanye quote API functionalities are implemented.

Frontende1

---

practiceapp/src/main/resources/application.yml
practiceapp/src/test/java/com/practiceapp/practiceapp/service/UserServiceTest.java

I mocked the profile class in the userService test class and add to the userService test class's saveUser test method. And it is solved and give me the successful result. Could you review the pull request pls.

UserServiceTest-ProfileBug-Solved

---

practiceapp/src/main/java/com/practiceapp/practiceapp/controller/universitieslist/UniversitiesListController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/service/CommunityService.java
practiceapp/src/main/java/com/practiceapp/practiceapp/utils/UniversitiesListApi.java
practiceapp/src/test/java/com/practiceapp/practiceapp/controller/community/GetCommunityControllerTest.java
practiceapp/src/test/java/com/practiceapp/practiceapp/controller/universitieslist/UniversitiesListControllerTest.java

Added:
1. GetCommunityControllerTest
2. UniversitiesListController Test
Updated:
1. UniversitiesListController
2. CommunityService
3. UniversitiesListApi
New return type of the UniversitiesListApi is List<String>. Made necessary changes in related classes.

Changing return type of UniversitiesList Api & Unit tests for the apis

---

practiceapp/src/main/java/com/practiceapp/practiceapp/controller/post/UpdatePostController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/service/PostService.java
practiceapp/src/test/java/com/practiceapp/practiceapp/controller/post/UpdatePostControllerTest.java
practiceapp/src/test/java/com/practiceapp/practiceapp/service/PostServiceTest.java

I've added those changes:
- Changed the return value of **updatePost** function from PostEntitiy class to integer to provide consistency with the **createPost** function.
- Created **UpdatePostControllerTest** which creates a new post object, gets its id, then sends a mock update request to the post with that id.  
- Added **updatePost** function to **PostServiceTest** file.
Although tests are running clean, I'm not sure whether the way I implemented the test in **UpdatePostControllerTest** is the proper way to do it or not. I seek your reviews, thanks in advance.

Implemented unit test for "Update Post" feature

---

practiceapp/src/main/java/com/practiceapp/practiceapp/controller/user/UserFollowController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/UserFollowViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/entity/UserEntity.java
practiceapp/src/main/java/com/practiceapp/practiceapp/service/UserService.java
practiceapp/src/main/resources/templates/follow_user.html

Added Controllers
* UserFollowController
* UserFollowViewController
Updated Entity
* User Entity (Follower and followed user is added to User Entity)
Added Html Pages
* follow_user.html

Following user functionality is added to Rest API. Frontend is implemented for following user functionality.

---

practiceapp/src/main/java/com/practiceapp/practiceapp/controller/profile/ProfileController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/AdviceViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/CreateUserViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/GetPlacesViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/IndexViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/ProfileViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/entity/CommunityEntity.java
practiceapp/src/main/java/com/practiceapp/practiceapp/entity/Profile.java
practiceapp/src/main/java/com/practiceapp/practiceapp/entity/UserEntity.java
practiceapp/src/main/java/com/practiceapp/practiceapp/repository/ProfileRepository.java
practiceapp/src/main/java/com/practiceapp/practiceapp/service/JoiningCommunityService.java
practiceapp/src/main/java/com/practiceapp/practiceapp/service/ProfileService.java
practiceapp/src/main/java/com/practiceapp/practiceapp/service/UserService.java
practiceapp/src/main/resources/templates/advice.html
practiceapp/src/main/resources/templates/getjoinedcommunities.html
practiceapp/src/main/resources/templates/getprofile.html
practiceapp/src/main/resources/templates/getuserbyname.html
practiceapp/src/main/resources/templates/index.html
practiceapp/src/main/resources/templates/saveuser.html
practiceapp/src/main/resources/templates/searchadvice.html
practiceapp/src/main/resources/templates/setrandompic.html
practiceapp/src/main/resources/templates/updateprofile.html
practiceapp/src/test/java/com/practiceapp/practiceapp/controller/joining/JoiningCommunityControllerTest.java
practiceapp/src/test/java/com/practiceapp/practiceapp/controller/post/CreatePostControllerTest.java
practiceapp/src/test/java/com/practiceapp/practiceapp/service/JoiningCommunityServiceTest.java

Added:
* JoiningCommunityControllerTest
* JoiningCommunityServiceTest
While implementing necessary classes, I had to add '@ToString.Exclude' annotations in UserEntity's joinedCommunities & createdCommunities lists and CommunityEntity's members list. The reason is, whenever Lombok's ToString method was called, it resulted in an circular reference in the lists above, therefore ending in a stack overflow error.

Unit Test Implementations for JoiningCommunityController and JoiningCommunityService

---

practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/CreateUserViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/DictionaryViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/GetCommunityViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/GetPostsViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/IndexViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/PostViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/ProfileViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/controller/views/UniversitiesViewController.java
practiceapp/src/main/java/com/practiceapp/practiceapp/service/PostService.java
practiceapp/src/main/resources/templates/community_search_form.html
practiceapp/src/main/resources/templates/create_post.html
practiceapp/src/main/resources/templates/dictionary_form.html
practiceapp/src/main/resources/templates/get_kanye.html
practiceapp/src/main/resources/templates/getjoinedcommunities.html
practiceapp/src/main/resources/templates/getprofile.html
practiceapp/src/main/resources/templates/getuserbyname.html
practiceapp/src/main/resources/templates/index.html
practiceapp/src/main/resources/templates/join_community.html
practiceapp/src/main/resources/templates/places_form.html
practiceapp/src/main/resources/templates/posts_search_form.html
practiceapp/src/main/resources/templates/saveuser.html
practiceapp/src/main/resources/templates/searchadvice.html
practiceapp/src/main/resources/templates/setrandompic.html
practiceapp/src/main/resources/templates/universities.html
practiceapp/src/main/resources/templates/universities_form.html
practiceapp/src/main/resources/templates/updateProfileForm.html
practiceapp/src/main/resources/templates/update_post.html
practiceapp/src/main/resources/templates/updateprofile.html

* I redirected the save user functionality to get profile functionality to make user see his/her profile immidiately. 
* Post search form added.
* **IndexViewController** is updated with new URL's.
* Save post functionality is connected to get posts of community to make user see his/her posts immidiately.
* Update Profile form is improved. It shows the old version of the profile at the beginning.
* **SetRandomPic** is connected to get profile functionality.
* **GetUniversities** UI added.
* Save Post functionality improved with setting date and updating the posts of target community.
* **getJoinedCommunities**, **getProfile**,  **updateProfile**, **getUser**, **saveUser**, **joinCommunity** templates are updated for standardizing UI.
* Exception handling mechanisms added to community …

Standardized the UI among different branches and implemeted additional connections

---

practiceapp/src/main/java/com/practiceapp/practiceapp/service/CommunityService.java

Fixed the bug in get definition function.
Now it returns a message if the word is not found instead of giving an error.

Fixed a bug in community service

---

mobile/CmpE451_App/src/constants.js
mobile/CmpE451_App/src/services/axiosCientService.js
mobile/CmpE451_App/src/theme/colors.js

- Moved constants to the directory _src/constants.js_
- Added axios configuration to the directory _src/services/axiosCientService.js_
- Moved colors to the directory _src/theme/colors.js_

Change project structure for constants, colors and axios

---

mobile/CmpE451_App/App.js
mobile/CmpE451_App/package-lock.json
mobile/CmpE451_App/package.json
mobile/CmpE451_App/src/AppNavigator.js
mobile/CmpE451_App/src/constants.js
mobile/CmpE451_App/src/screen/Chat.js
mobile/CmpE451_App/src/screen/CreateCommunity.js
mobile/CmpE451_App/src/screen/Login.js
mobile/CmpE451_App/src/screen/Logout.js
mobile/CmpE451_App/src/screen/Main.js
mobile/CmpE451_App/src/screen/Notification.js
mobile/CmpE451_App/src/screen/Profile.js
mobile/CmpE451_App/src/screen/Settings.js
mobile/CmpE451_App/src/services/axiosCientService.js
mobile/CmpE451_App/src/theme/colors.js
mobile/CmpE451_App/src/theme/styles.js

Added left drawer which navigates to
- Home
- Profile
- Create Community 
- Settings
- Logout
Closes #200

Add left navigator to the mobile

---

mobile/CmpE451_App/package-lock.json
mobile/CmpE451_App/package.json
mobile/CmpE451_App/src/AppNavigator.js
mobile/CmpE451_App/src/constants.js
mobile/CmpE451_App/src/screen/SelectCommunity.js
mobile/CmpE451_App/src/screen/SelectDataType.js
mobile/CmpE451_App/src/theme/colors.js

Added choose community page.
Page can be accessed from the bottom tab navigator.
It lists communities that can be selected by pressing.
Closes #214

Add choose a community page

---

mobile/CmpE451_App/src/AppNavigator.js
mobile/CmpE451_App/src/constants.js
mobile/CmpE451_App/src/screen/Login.js
mobile/CmpE451_App/src/screen/SelectCommunity.js
mobile/CmpE451_App/src/screen/SelectDataType.js
mobile/CmpE451_App/src/screen/SelectPostType.js
mobile/CmpE451_App/src/services/axiosCientService.js

Added choose post type (data type) page. 
Page can be accessed from the _choose community_ page.
It lists post types that can be selected by pressing.
Closes #221

Mobile: Choose Post Type Page

---

mobile/CmpE451_App/package-lock.json
mobile/CmpE451_App/package.json
mobile/CmpE451_App/src/AppNavigator.js
mobile/CmpE451_App/src/constants.js
mobile/CmpE451_App/src/screen/CreatePostType.js
mobile/CmpE451_App/src/screen/SelectModeratorCommunity.js

Designed and implemented creating post type(data type) functionality. 
Added two pages:
- Choosing Community Page (_SelectModeratorCommunity.js_)
- Creating Data Type Page (_CreatePostType.js_)
as #226 suggested
Closes #226.

Add create post type functionality

---

backend/resource/swagger.yaml

Added communities endpoint and made improvements in general.
Closes #230

Improve Spec Swagger YAML

---

backend/.eslintrc.json
backend/resource/swagger.json
backend/src/app.js
backend/src/controllers/auth.controller.js
backend/src/middlewares/error.js
backend/src/middlewares/validate.js
backend/src/routes/auth.route.js
backend/src/services/auth.service.js
backend/src/utils/formatters.js
backend/src/validations/auth.validation.js

Register, login, logout endpoints are completed. Solves #233

Auth endpoints

---

backend/src/controllers/post.controller.js
backend/src/controllers/postType.controller.js
backend/src/models/user.js
backend/src/routes/post.route.js
backend/src/routes/postType.route.js
backend/src/services/post.service.js
backend/src/services/postType.service.js
backend/src/utils/formatters.js
backend/src/validations/post.validation.js
backend/src/validations/postType.validation.js

I implemented the controller and service functions for both getting post and post type details.
I also added validation and formation of output functions for both of them.
Validation functions check if the given parameters are in the correct form.
Form functions design the output format.
The requests:
GET Request 
/posts/detail 
query parameters: communityId & postId
GET Request 
/post-types/detail 
query parameters: communityId & postTypeId

Implementation of Getting Post Details and Post Type Details

---

web/src/components/NavBar.js

I implemented the navigation bar for our website. The navigation bar contains elements as described in issue #223. Closes #223.

Implementing Navigation Bar Design

---

web/src/components/AboutCommunity.js

I implemented the About Community component for our website. The component displays general information about given community. Could you please review my work? Thanks in advance. closes #240

Implementing the About Community Component

---

web/src/components/CreateCommunity.js

I implemented the create community component. The component contains a form that takes input as described in the #244. Could you please review my work? Thanks in advance. closes #244

Implementing the Create Community Component

---

mobile/CmpE451_App/package-lock.json
mobile/CmpE451_App/package.json
mobile/CmpE451_App/src/AppNavigator.js
mobile/CmpE451_App/src/constants.js
mobile/CmpE451_App/src/screen/PostDetail.js

Implemented logout functionality. Please review.
closes #242

Mobile: Logout

---

mobile/CmpE451_App/app.json
mobile/CmpE451_App/src/AppNavigator.js
mobile/CmpE451_App/src/screen/CreatePostType.js
mobile/CmpE451_App/src/screen/Login.js
mobile/CmpE451_App/src/screen/SelectCommunity.js
mobile/CmpE451_App/src/screen/SelectModeratorCommunity.js
mobile/CmpE451_App/src/screen/SelectPostType.js
mobile/package-lock.json
package-lock.json

Requests:
- login
- post-types : post 
- post-types : get
- communities: get
are updated as #241 indicates.
Wordings are changed as post type and community.
Closes #241

Update requests based on the Swagger

---

mobile/CmpE451_App/.gitignore
mobile/CmpE451_App/android/app/src/main/java/com/cmpe451_app/MainApplication.java
mobile/CmpE451_App/android/settings.gradle
mobile/CmpE451_App/ios/Podfile
mobile/CmpE451_App/package-lock.json
mobile/CmpE451_App/package.json
mobile/CmpE451_App/src/AppNavigator.js
mobile/CmpE451_App/src/constants.js
mobile/CmpE451_App/src/screen/CreateCommunity.js
mobile/CmpE451_App/src/screen/CreatePostType.js
mobile/CmpE451_App/src/screen/Login.js
mobile/CmpE451_App/src/screen/Registration.js
mobile/CmpE451_App/src/screen/SelectCommunity.js
mobile/CmpE451_App/src/screen/SelectModeratorCommunity.js
mobile/CmpE451_App/src/screen/SelectPostType.js
mobile/CmpE451_App/src/services/asyncStorageService.js
mobile/CmpE451_App/src/services/axiosCientService.js
mobile/CmpE451_App/src/util/Reguests.js
mobile/CmpE451_App/yarn.lock

Tokens are stored in the async storage. Async storage service is implemented with _getToken_ , _storeToken_ , _removeToken_
Closes #271

Use async storage for token

---

backend/src/controllers/community.controller.js
backend/src/models/community.js
backend/src/services/community.service.js
backend/src/utils/formatters.js

description and isPrivate fields are added to the community model and its endpoints such as createCommunity parameters and getCommunity outputs.

Community model fix: description and isPrivate added

---

mobile/CmpE451_App/src/component/DynamicFormField.js
mobile/CmpE451_App/src/screen/CreatePost.js

Location data is updated:
```JSON
{
"name": "", 
"value": { 
"geo": {
"latitude": 0, 
"longitude": 0
}, 
"description": ""
}
}
```

Update Location Data Structure for Create Post

---

mobile/CmpE451_App/src/screen/CreateCommunity.js
mobile/CmpE451_App/src/services/BoxyClient.js

- Added input text for description and switch for privacy option.
- Request handler is moved to the _BoxyClient.js_
- Improved design by using common styles and components.
Closes #308

Mobile: Create Community Enhancement

---

backend/resource/swagger.json

I updated the swagger doc according to new changes in Location field.
I added new Location, User models

Swagger doc updated

---

mobile/CmpE451_App/src/component/CloseButton.js
mobile/CmpE451_App/src/component/DeleteButton.js
mobile/CmpE451_App/src/screen/CreatePostType.js
mobile/CmpE451_App/src/screen/SelectModeratorCommunity.js

The design of the **_Choose Moderator Community_** and **_Create Post Type_** screens are improved. 
The _**delete button**_ component is created.
Solves #318

Mobile: Update Choose Community and Create Post Type Design 

---

backend/src/controllers/community.controller.js
backend/src/controllers/post.controller.js
backend/src/controllers/profile.controller.js
backend/src/models/post.js
backend/src/models/user.js
backend/src/routes/community.route.js
backend/src/routes/post.route.js
backend/src/routes/profile.route.js
backend/src/services/community.service.js
backend/src/services/post.service.js
backend/src/services/profile.service.js
backend/src/utils/formatters.js

likeCount field is added to the response of post detail.
members and moderators fields are added to the response of community detail.
Getting somebody else's profile, leaving community and liking post endpoints are implemented. They are tested before the commits.

Backend: Milestone 2 Updates

---

mobile/CmpE451_App/src/screen/Community.js
mobile/CmpE451_App/src/services/BoxyClient.js

The Join community functionality is implemented.
Users can join by pressing the _Join Community_ button.
Closes #320

Mobile: Join Community Functionality

---

mobile/CmpE451_App/src/screen/Settings.js

Settings page is implemented with following sections:
* Account (will be implemented after backend)
- Update Username
- Update Email Address
- Change Password
- Delete Account
* About
- Terms and Conditions:
- Generate and link
- Privacy Policy
* Support
- Contact Us
- Version
**Terms and Conditions** and **Privacy Policy** texts are generated. These sections are linked to the deployed versions.
Closes #325

Mobile: Settings Screen

---

mobile/CmpE451_App/src/component/DeleteButton.js
mobile/CmpE451_App/src/component/HomeButton.js
mobile/CmpE451_App/src/component/ScreenHeader.js
mobile/CmpE451_App/src/screen/Communities.js
mobile/CmpE451_App/src/screen/Community.js
mobile/CmpE451_App/src/screen/CreateCommunity.js
mobile/CmpE451_App/src/screen/CreatePost.js
mobile/CmpE451_App/src/screen/CreatePostType.js
mobile/CmpE451_App/src/screen/SelectCommunity.js
mobile/CmpE451_App/src/screen/SelectModeratorCommunity.js
mobile/CmpE451_App/src/screen/SelectPostType.js
mobile/CmpE451_App/src/screen/Settings.js
mobile/CmpE451_App/src/theme/colors.js
mobile/CmpE451_App/src/theme/styles.js

The page header is designed and implemented as a component. 
Parameters for the component:
- Title component
- Icon name from the [material design icons](https://materialdesignicons.com/)
- function for navigation.
The home page icon is used for navigating the home page. 
The back icon is used for navigating back. 
Closes #344

Mobile: Page header component

---

backend/src/controllers/community.controller.js
backend/src/routes/community.route.js
backend/src/services/community.service.js
backend/src/utils/baseUtil.js
backend/src/validations/community.validation.js

approve and reject endpoints for join requests

---

backend/src/controllers/community.controller.js
backend/src/models/community.js
backend/src/routes/community.route.js
backend/src/services/community.service.js
backend/src/utils/formatters.js

endpoint to become a mod

---

mobile/CmpE451_App/src/AppNavigator.js
mobile/CmpE451_App/src/component/CommonIcon.js
mobile/CmpE451_App/src/component/UserList.js
mobile/CmpE451_App/src/screen/Community.js
mobile/CmpE451_App/src/screen/PendingRequests.js
mobile/CmpE451_App/src/services/BoxyClient.js

Implemented accept/reject join community requests for the moderators.
- Implemented a page that is only visible for the moderators to list. 
- Created a common icon button component.
- Implemented handler to accept or reject the pending requests.
- The page is accessible from the community detail page by clicking the notification icon.
- A pending icon appears when a user tries to join a private community.
Closes #361

Mobile: Add Accept & Reject Join Community Request Functionality

---

backend/src/controllers/community.controller.js
backend/src/routes/community.route.js
backend/src/services/community.service.js

approve and reject endpoints for moderator requests

---

mobile/CmpE451_App/package-lock.json
mobile/CmpE451_App/src/screen/Community.js
mobile/CmpE451_App/src/screen/PendingRequests.js
mobile/CmpE451_App/src/services/BoxyClient.js
mobile/CmpE451_App/yarn.lock

The leave community functionality is implemented.
Closes #369

Mobile: Leave community

---

mobile/CmpE451_App/src/component/TabScreen.js
mobile/CmpE451_App/src/component/UserList.js
mobile/CmpE451_App/src/screen/Community.js
mobile/CmpE451_App/src/services/BoxyClient.js

**Implemented kicking a community member from the community functionality.**
For community moderators, a kick icon is added next to the community members' names. Moderators can kick members by clicking this icon. Community moderators can not be kicked.
Closes #372

Mobile: Kick Member From Community

---

mobile/CmpE451_App/src/AppNavigator.js
mobile/CmpE451_App/src/screen/Community.js
mobile/CmpE451_App/src/screen/UpdateCommunity.js
mobile/CmpE451_App/src/services/BoxyClient.js

Update Community functionality is implemented.
The form includes Community Name, Community Photo URL, Community Description, Community Privacy option.
When it is first opened, the form is filled with as-is data.
Closes #374

Mobile: Update Community

---

mobile/CmpE451_App/src/screen/Community.js
mobile/CmpE451_App/src/screen/CreatePost.js
mobile/CmpE451_App/src/services/BoxyClient.js

Implemented applying to be moderator functionality in community detail. 
Closes #376

Mobile: Add request to be moderator functionality

---

mobile/CmpE451_App/src/AppNavigator.js
mobile/CmpE451_App/src/screen/Settings.js
mobile/CmpE451_App/src/services/BoxyClient.js

Delete Account functionality is implemented. 
Users can delete their accounts from the delete account item on the settings page. 
Closes #386

Mobile: Delete Account

---

web/src/components/AboutCommunity.js
web/src/components/CreatePost.js
web/src/components/CreatePostType.js
web/src/components/PostView.js
web/src/components/ProfileEdit.js
web/src/pages/GetCommunityPage.js
web/src/pages/ProfilePage.js
web/src/routing/RouteList.js
web/src/store/axios.js
web/src/store/urls.js
web/src/utils/helper.js

We have implemented the other user's route and connected user profiles with post pages.  Please review.

Add other users and connect post and profile pages

---

web/src/components/CreateCommunity.js
web/src/components/CreatePost.js
web/src/components/FieldContent.js
web/src/pages/ProfilePage.js

Fixed post locations please review.

Fix location in posts

---

backend/resource/swagger.json

swagger-update

---

mobile/CmpE451_App/src/screen/UpdateCommunity.js
mobile/CmpE451_App/src/services/BoxyClient.js

The **delete community** functionality is implemented for the community moderators. 
The delete operation can be done from the update community page.
Closes #429

Mobile: Delete Community Functionality

---

mobile/CmpE451_App/src/component/PostDetail.js
mobile/CmpE451_App/src/screen/Community.js
mobile/CmpE451_App/src/screen/Main.js
mobile/CmpE451_App/src/screen/PostDetail.js
mobile/CmpE451_App/src/services/BoxyClient.js

The like post functionality is implemented. 
Users can like posts by pressing the like button. 
Please review the changes.
Closes #433

Mobile: Like Post

---

mobile/CmpE451_App/src/component/Comment.js
mobile/CmpE451_App/src/component/PostDetail.js
mobile/CmpE451_App/src/screen/Main.js
mobile/CmpE451_App/src/screen/PostDetail.js
mobile/CmpE451_App/src/services/BoxyClient.js

Designed and implemented **view** and **create** **comments** functionality.
Created _comment.js_ component for comment view and added a text input field to the _post detail component_ for creating a comment.
Updated _home_ and _post detail_ screens accordingly.
Closes #444, #445

Mobile: View and Create Comments

---

mobile/CmpE451_App/src/component/PostDetail.js
mobile/CmpE451_App/src/component/SearchBar.js
mobile/CmpE451_App/src/screen/Main.js

The search Bar component is implemented and added to the home page.
On press, it navigates to the search page.
Closes #459

Mobile: Search bar component

---

mobile/CmpE451_App/package-lock.json
mobile/CmpE451_App/package.json
mobile/CmpE451_App/src/AppNavigator.js
mobile/CmpE451_App/src/component/SearchBar.js
mobile/CmpE451_App/src/component/SearchResult.js
mobile/CmpE451_App/src/screen/Search.js
mobile/CmpE451_App/src/services/BoxyClient.js
mobile/CmpE451_App/yarn.lock

- The **search community** functionality is implemented. 
- The search result component is implemented for users and communities.
Closes #461

Mobile: Implementing Searching Community Functionality

---

backend/src/controllers/wikidata.controller.js
backend/src/routes/index.js
backend/src/routes/wikidata.route.js
backend/src/services/post.service.js

Wikidata endpoint is implemented.
URI: https://api.cmpegroupthree.store/wikidata?query=
query can be text or tag id

Backend: Wikidata Endpoint Implementation

---

backend/src/models/post.js
backend/src/services/post.service.js
backend/src/validations/post.validation.js

Tag structure is renewed.
tags: [ { id: "string", name: "string" } ]
Also, searching posts by tags updated. Users can search posts by searching tag names.

Backend: tags structure renew

---

web/package-lock.json
web/package.json
web/src/components/AboutCommunity.js
web/src/components/CommunityModeration.js
web/src/components/CreateCommunity.js
web/src/components/CreatePostType.js
web/src/components/GetPostTypes.js
web/src/components/NavBar.js
web/src/components/PostView.js
web/src/pages/GetCommunityPage.js
web/src/pages/HomePage.js
web/src/store/axios.js
web/src/store/urls.js
web/src/utils/helper.js

I have implemented the changes requested in #419 . I will add some screenshots of the design. Please review.

Implementation for Web: Community Specific Search

---

web/package-lock.json
web/package.json
web/src/components/PostView.js
web/src/pages/HomePage.js
web/src/store/axios.js
web/src/store/urls.js
web/src/utils/helper.js

I have implemented the tag viewing on community posts requested in #420 . The wikidata connection has not been implemented yet, but the functionality of the tags is ready. Please review.

Implement tags for viewing posts

---

mobile/CmpE451_App/src/component/SearchResult.js
mobile/CmpE451_App/src/screen/Search.js
mobile/CmpE451_App/src/services/BoxyClient.js

The **search user** functionality is implemented.
Users can search other users from the search bar selecting the _user option_ from the drop-down. 
Implemented a method to send a search request to the backend in BoxyClient.js
Closes #462

Mobile: Searching User Functionality

---

web/src/components/PostView.js
web/src/store/axios.js
web/src/store/urls.js
web/src/utils/helper.js

I have implemented the updates requested in #420 since we have changed the way tags work in our projects. Please review.

Update tag routes and post viewing

---

web/src/components/PostView.js
web/src/pages/GetCommunityPage.js
web/src/store/axios.js
web/src/store/urls.js
web/src/utils/helper.js

I have implemented the changes requested in #456 . I've tested the connection between the backend and the functionality of the feature. Please review.

Implementation for Web: Community Posts Sort 

---

web/package-lock.json
web/src/components/CommentView.js
web/src/components/PostView.js
web/src/pages/GetPostPage.js
web/src/store/axios.js
web/src/store/urls.js
web/src/utils/helper.js

I implemented the following features:
* Seeing the list of comments in the post page
* Navigating to the profile page of the owner of a comment
* Posting new comments
* Liking posts
Please review my work. Thanks in advance!
Closes #453 
Closes #454 
Closes #455

Web: Comment Features Implementation

---

web/src/components/CreatePost.js
web/src/components/CreatePostType.js
web/src/components/GetPostTypes.js
web/src/components/PostView.js
web/src/components/ProfileEdit.js
web/src/store/axios.js

I have implemented the changes requested in #467 . You can see the design from the screenshot. Please review.

Implementation for Web: Post Creation Tags

---

backend/src/services/post.service.js
backend/src/validations/post.validation.js

makes advanced search start and end variables optional

---

backend/src/controllers/post.controller.js
backend/src/routes/post.route.js
backend/src/services/post.service.js
backend/src/validations/post.validation.js

Remove like from a post endpoint is implemented.
Get: /unlike
parameters: postId and communityId

Backend: Remove like endpoint

---

backend/src/services/post.service.js

There was a bug. LikeCount update was forgotten. It is implemented.

Backend: likeCount update fix

---

mobile/CmpE451_App/src/screen/CommunitySearch.js
mobile/CmpE451_App/src/screen/PostSearchResults.js
mobile/CmpE451_App/src/services/BoxyClient.js

- Implemented basic post search on the community's search page.
- Implemented request handler for basic post search.
Users can search posts without specifying a post type.
Closes #500

Mobile: Basic Post Search

---

backend/resource/swagger.json

Swagger doc updated according to the new changes in tag structure, Wikidata, comments

Backend: Swagger doc update

---

web/src/components/AboutCommunity.js
web/src/components/CreatePost.js
web/src/components/PostFilter.js
web/src/pages/GetCommunityPage.js
web/src/store/axios.js
web/src/store/urls.js
web/src/utils/helper.js

I have implemented the features requested in #477 . You can check out the screenshot for the design. Please review.

Implementation for Web: Advanced Post Search

---

web/src/components/AboutCommunity.js
web/src/components/CreatePost.js
web/src/components/GetCommunities.js
web/src/components/PostFilter.js
web/src/components/PostView.js
web/src/pages/GetCommunityPage.js
web/src/pages/HomePage.js
web/src/routing/RouteList.js
web/src/store/axios.js
web/src/store/urls.js
web/src/utils/helper.js

I have implemented the changes requested in #497 and #510 . Here is an example screenshot from deleting posts. Please review.

Web: Implement Delete Post & Fix Community Leave

---

backend/src/controllers/profile.controller.js
backend/src/routes/profile.route.js
backend/src/services/community.service.js
backend/src/services/profile.service.js
backend/src/utils/formatters.js

Get notification endpoint is implemented.
Get
profile/notification

Backend: Notification Endpoint

---

web/src/components/CommentView.js
web/src/pages/GetPostPage.js

Implemented the changes requested in #512 . Here is a design ss. Please review.

Enhancement for Web: Comments Design

---

backend/src/models/activityStream/commentACS.js
backend/src/models/activityStream/communityACS.js
backend/src/models/activityStream/postACS.js
backend/src/models/activityStream/postTypeACS.js
backend/src/models/activityStream/userACS.js
backend/src/services/profile.service.js
backend/src/utils/formatters.js

Response example:
[
{
"summary": "Zgocbrayt accepted your join request to the community Experienced Dancers",
"createdAt": "2021-12-30T23:48:30.327Z",
"actor": "61c274571ee8f909f5e544aa",
"object": "61b7d41471875d636db47f6e",
"objectType": "Community"
} ]

Backend: Notifications now have objects and actors

---

mobile/CmpE451_App/src/component/PostDetail.js
mobile/CmpE451_App/src/screen/PostDetail.js
mobile/CmpE451_App/src/services/BoxyClient.js

Added community id to like post request as query parameter.
Closes #524

Mobile: Add Community ID to Like Post Request

---

mobile/CmpE451_App/src/component/CommunityPosts.js
mobile/CmpE451_App/src/component/PostDetail.js
mobile/CmpE451_App/src/screen/Community.js
mobile/CmpE451_App/src/screen/PostDetail.js
mobile/CmpE451_App/src/services/BoxyClient.js

The community posts component is updated to use the community detail component. 
Improved the design by resizing the community detail background.
Closes #526

Mobile: Using Post Detail component for Community Posts

---

web/src/components/CommentView.js
web/src/components/NavBar.js
web/src/components/NotificationView.js
web/src/components/PostView.js
web/src/pages/NotificationsPage.js
web/src/routing/RouteList.js
web/src/store/axios.js
web/src/store/urls.js
web/src/utils/helper.js

I have implemented the changes requested in #421 . I will add a screenshot. Please review.

Implementation for Web: Community Notifications / Activity Stream

---

mobile/CmpE451_App/src/screen/Settings.js
mobile/CmpE451_App/src/services/BoxyClient.js

- Added change password request handler to the `BoxyClient.js`
- Implemented change password functionality on the `Settings.js`
Closes #534

Mobile: Change Password

---

mobile/CmpE451_App/src/screen/Settings.js

Added alert to warn users before deleting their account.
Closes #535

Mobile: Add alert before deleting account

---

backend/src/utils/formatters.js

Pending followers field in the response is fixed. user id is added to the response.

Backend: Pending followers fix

---

web/src/components/AboutCommunity.js
web/src/components/CommunityModeration.js
web/src/components/NotificationView.js
web/src/components/ProfileEdit.js
web/src/components/ProfileModeration.js
web/src/components/ProfileView.js
web/src/pages/GetCommunityPage.js
web/src/store/axios.js
web/src/store/urls.js
web/src/utils/helper.js

I have implemented the changes requested in #522 and #521. The functionality changes when the followed user has a public or private profile. You can find screenshots for each case below. Please review.

Implementation for Web: User Follow Accept / Reject / Follow / Unfollow

---

web/src/components/PostView.js
web/src/store/axios.js
web/src/store/urls.js
web/src/utils/helper.js

Implemented the feature of disliking posts. Fixed the endpoint query parameters for the like and dislike endpoints. Please review my work. Thanks in advance.
Closes #518 
Closes #540

Implementation of dislike feature & like dislike fix

---

mobile/CmpE451_App/App.js

The status bar is added to improve the design.
Closes #549

Mobile: Add status  bar

---

mobile/CmpE451_App/src/component/PostDetail.js
mobile/CmpE451_App/src/screen/Community.js
mobile/CmpE451_App/src/screen/CreatePost.js
mobile/CmpE451_App/src/screen/Main.js
mobile/CmpE451_App/src/screen/PostDetail.js
mobile/CmpE451_App/src/screen/PostSearchResults.js
mobile/CmpE451_App/src/screen/Profile.js
mobile/CmpE451_App/src/services/BoxyClient.js

Delete post functionality is implemented.
* Users can delete their posts viewing their own posts and clicking the delete icon.
* Posts of communities can be deleted by the moderators by viewing posts from the community page.
Closes #381

Mobile: Delete Post

---

backend/src/config/config.js
backend/src/services/community.service.js
backend/src/services/post.service.js
backend/src/services/profile.service.js
backend/src/utils/formatters.js

When an object is pulled from a list, its count is decremented. 
When an object is added to a list, its count is incremented.

Backend: Counts inc & dec - bug fix

---

backend/src/models/community.js
backend/src/services/post.service.js

* Checks if the user is a member of the community, then returns the posts.
* MemberCount default is 1 because somebody is creating the community.

Backend: Bug fixes 

---

mobile/CmpE451_App/src/screen/ProfileSettings.js

User can select if follow request should sent someone to follow them.
It can be set from the profile settings page.
closes #569

Mobile: Follow privacy

---

backend/src/utils/formatters.js

UserPreview formatter was not able to return profilePhotoUrl value. It is fixed.

Backend: profilePhoto fix

---

mobile/CmpE451_App/src/component/PostDetail.js

Implemented navigation to profile from post detail.
Closes #571

Mobile: Add Navigation to Profile from Post Detail

---

mobile/CmpE451_App/src/component/CommunityPosts.js
mobile/CmpE451_App/src/component/PostDetail.js
mobile/CmpE451_App/src/screen/Main.js
mobile/CmpE451_App/src/screen/PostDetail.js

The post type name is added to the post detail component.
Closes #575

Mobile: Add post type names to the posts

---

backend/src/services/profile.service.js
backend/src/utils/formatters.js

* When someone follows or sends request, notification should be created.
* followerCount is added to the response for creator of the community.

Backend: Follow notification fix 

---

backend/src/services/profile.service.js

Actor and object is reversed in follow activity stream.

Backend: bug fix

---

backend/src/utils/formatters.js

Get other profile used to return wrong followerCount. it is fixed.

Backend: followerCount bug fix

---

backend/src/services/post.service.js

Delete post was not working properly because of the if statement. it is fixed and tested. works perfectly.

Backend: delete post bug fix

---

backend/src/controllers/acs.controller.js
backend/src/routes/docs.route.js
backend/src/services/acs.service.js
backend/src/services/index.js
backend/src/utils/formatters.js

We've already implemented activity stream. Also, notifications are based on activity streams. 
However, we needed an API call to see the Activity Stream JSON.

Backend: acs JSON return API

---

backend/resource/swagger.json

* Activity Stream APIs 
* Notification API
* Activity Stream Models
are documented in Swagger doc.

Documentation: Swagger Update
